services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=tinderfordogs
      - POSTGRES_PASSWORD=${TINDER4DOGS_POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'
