package com.ai4dev.tinderfordogs.support.presentation

import com.ai4dev.tinderfordogs.ai.common.service.Message
import com.ai4dev.tinderfordogs.support.service.ModelComparison
import com.ai4dev.tinderfordogs.support.service.SupportAssistantService
import com.ai4dev.tinderfordogs.support.service.SupportEvaluationService
import org.springframework.beans.factory.annotation.Value
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

data class SupportRequest(
    val message: String,
    val history: List<Message> = emptyList(),
)

data class SupportResponse(
    val answer: String,
    val model: String,
)

/**
 * REST controller responsible for handling AI-powered support interactions within the Tinder for Dogs application.
 *
 * Exposes endpoints under `/api/v1/support` that allow clients to ask questions to the support
 * assistant and to compare responses between a fine-tuned support model and a base language model.
 *
 * Support answers are generated by [SupportAssistantService] using the configured model identified
 * by the `tinder4dogs.support.model` property. Conversation history can be included in requests
 * to maintain context across multiple turns.
 *
 * Model evaluation is handled by [SupportEvaluationService], which sends the same message to both
 * the fine-tuned support assistant and a base model, returning both responses side by side for
 * comparison purposes.
 *
 * @param support the service responsible for generating answers using the support assistant model
 * @param evaluation the service responsible for comparing fine-tuned and base model responses
 * @param model the name of the configured support assistant model, injected from application properties
 */
@RestController
@RequestMapping("/api/v1/support")
class SupportController(
    private val support: SupportAssistantService,
    private val evaluation: SupportEvaluationService,
    @Value($$"${tinder4dogs.support.model}")
    private val model: String,
) {
    @PostMapping("/ask")
    suspend fun ask(
        @RequestBody req: SupportRequest,
    ): SupportResponse =
        SupportResponse(
            answer = support.answer(req.message, req.history),
            model = model,
        )

    @PostMapping("/compare")
    suspend fun compareTo(
        @RequestBody req: SupportRequest,
    ): ModelComparison = evaluation.compare(req.message)
}
